### ISSUE TITLE
USER STORY: AI assistant

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#10]
As a website user, I can get a suggestion for a route from an AI assistant so that I receive an optimised route to work and cycle safer to work

## Acceptance Criteria: 

-  User creates a route using the conventional way of providing start and end location 
- user can input prompts to modify the route based their verbal input 

## Tasks:

- [ ] (FE) add UI elements such as ’suggest a route with AI’ button
- [ ] (FE) add UI elements display a suggested route , or several suggested routes 
- [ ] (FE) add UI elements for user to prompt and change the route based on their input 
- [ ] (BE) Add functionality to send information to API calculating an optimised route based on the input
