### ISSUE TITLE
USER STORY: Share Routes

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#11]
As a website user, I can make my route to work public and share the route with other users so that other user may find interesting and perhaps more safe new cycling routes to work

## Acceptance Criteria: 

-  user can click on UI element such as a checkbox to make the route public available for others 
-  when changing status between 'private' and 'public', a UI feedback element such as a toast appears to inform the user about the action
- 
## Tasks:

- [ ] (FE) create button or other UI element so that user can publish their route for others, i.e. using a ‘publish’ button or checkbox ’
- [ ] (FE) create UI elements for adding coordinates of a route to work on an interactive map 
- [ ] (FE) create UI elements visual feedback (i.e. a toast message) when user changes privacy state of their route 
- [ ] (BE) Add URLs, views to for publishing a route 
- [ ] (BE) Update model field with a ‘is_public’ field and allow access to route for other users
