### ISSUE TITLE
USER STORY: Save Routes

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#12]
As a website user, I can save my route to work so that I can retrieve the information on other days

## Acceptance Criteria: 

-  once entered a route, the user can click on a button and save the route 
- the route is stored in the DB for that user and available when the user logs in again 

## Tasks:

- [ ] (FE) create UI elements for ‘save’ and ‘discard’ buttons 
- [ ] (BE) Add URLs, views to display a stored route 
- [ ] (BE) Add Model for Route and design a way to store the routes efficiently in a DB table
