### ISSUE TITLE
USER STORY: Create Routes

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#13]
As a website user, I can add coordinates for my home and work place so that I can plan a cycle route to work using the Route Planner page

## Acceptance Criteria: 

- User can define endpoints of the route either by clicking on the map or via input locations in a text field 
- after clicking 'calculate Route' a route is drawn on the map 

## Tasks:

- [ ] (FE) create UI and page for routes to work 
- [ ] (FE) create UI elements for adding coordinates of a route to work on an interactive map 
- [ ] (FE) add input fields for start and end addresses 
- [ ] (FE) add Javascript functionality to calculate optimised cycling path to work, i.e. by calling an API mapping service
