### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#14]
As an site admin, I can delete Products from the Shop  so that make products hidden from the users if they run out of stock or if I wish to delete them 

## Acceptance Criteria: 

- When logged in as admin, there appears a new UI element such as an ‘delete’ button on the product detail page 
- When clicking on ‘delete button’ button, a confirmation dialog appears including a warning that this operation cannot be undone 
- If the user confirms, the product is
- If the input is valid, a UI element such as toast should appear with a success message
- In the admin panel, the product that was deleted cannot be found any more  confirming its deletion from the DB
- 

## Tasks:

- [x] (FE) create UI elements for ‘delete’ buttons on the product detail page 
- [x] (FE) add forms to UI layout 
- [x] (FE) add UI elements for deleting products including a confirmation dialog where the user confirms the deletion and is warned that this operation cannot be undone 
- [x] (FE) add visual feedback i.e. in form of toast after successful deleting to shopping bag 
- [x] (BE) create form for deleting product to DB into template
- [x] (BE) add views for deleting   product to DB  
- [x] (BE) add views for deleting item from product table in  DB  
- [ ]
