### ISSUE TITLE
USER STORY: Update  Products

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#15]
As an site admin, I can add update Products in the Shop  so that have keep the information updated 

## Acceptance Criteria: 

- When logged in as admin, there appears a new UI element such as an ‘update’ button on the product detail page 
- When clicking on ‘save changes’ button, the product is updated according to the changes (i.e. price, description, name)
- If the input is invalid, a UI element such as toast should appear with a warning containing the error 
- If the input is valid, a UI element such as toast should appear with a success message  
- In the admin panel, the changes to the product are confirmed

## Tasks:

- [x] (FE) create UI elements for ‘update’ buttons on the product detail page 
- [x] (FE) add forms to UI layout 
- [x] (FE) add UI elements for updating products including a ‘save changes’ and ‘cancel’ button
- [x] (FE) add visual feedback i.e. in form of toast after successful updating shopping bag 
- [x] (BE) create form for updating product to DB into template
- [x] (BE) add views for updating product table in  DB
