### ISSUE TITLE
USER STORY: Add Product

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#16]
As an site admin, I can add a Product to the Shop  so that have new products in my shop

## Acceptance Criteria: 

- when logged in as admin, a new link appears on the navbar for shop administration 
-  When clicking on the link, a page opens with a form to enter a new product 
- When clicking on the button and entering valid details, the newly added product is added to the shop with the provided details (price, description, category etc. )

## Tasks:

- [x] (FE) create UI elements such as ‘add’ buttons or buttons to change quantity on product detail form and on the preview
- [x] (FE) add form to UI layout 
- [x] (FE) add visual feedback i.e. in form of toast after successful adding to shopping bag 
- [x] (BE) create form for adding product to DB into template
- [x] (BE) add views for adding product to DB  
- [x] (BE) add model for product
