### ISSUE TITLE
USER STORY: Preview Shopping Bag

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#19]
As a website user, I can preview the items of the shopping bag while being on the main shop page so that I can keep shopping for more products while having already selected other products

## Acceptance Criteria: 

- when the user clicks on the  ‘add to shopping bag’ button, the product is visible in the preview of the shopping bag 
- The added product is also included in the detail view of the shopping bag  
- 

## Tasks:

- [x] (FE) create UI elements click on a clearly visible shopping bag icon in the navbar to get a detail view of the shopping bag
- [x] (FE) create UI element for the bag detail page
- [x] (BE) add URLs, forms and views to render the checkout page
