### ISSUE TITLE
USER STORY: SEO

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#20]
As a website user, I can enter certain keywords in Google  so that I can find the websites on Google easily via keywords on the first page of Google

## Acceptance Criteria: 

- robots and sitemap file present 
-  404 page present and routed to when user provides invalid URL
- every link has correct meta attributes 
- all required meta keywords (title, keywords ) are meaningful and express intention of the website 
- all images have meaningful alt attribute 

## Tasks:

- [x] add robots.txt and sitemap 
- [x] Include 404 page 
- [x] Ensure external links are marked correctly
- [x] Ensure all images have meaningful alt descriptions
- [x] Run and document a keyword search related to the shop
