### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#21]
As a website user, I can signup for newsletter with my Email address so that I can receive discounts or other offers via Email 

## Acceptance Criteria: 

- on the main page, user can find a CTA where they can sign up to a newsletter 
- After adding valid Email address and clicking to sign up, the user email should be in the DB and appear on mail chimp as signed up user 
- A toast appears when signup was successful 
- A warning toast appear if email is invalid 

## Tasks:

- [x] (FE) create UI elements for viewing newsletter signup 
- [x] (FE) add visual feedback i.e.  in form of toast after successful signup , or if provided text is not a valid email 
- [x] (BE) add forms and views to add email address to DB for mailchimp
- [ ] (BE) add model for newsletter
