### ISSUE TITLE
USER STORY: Update Response to Comment

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#22]
As an site admin, I can update or delete the response to a product comment  so that I can correct mistakes or add more info after saving the response

## Acceptance Criteria: 

- on the comment review page, the admin can click on a button to ‘edit response’ 
- After clicking button, a text field appears with the response, and the admin can edit it 
- If clicking on ‘save changes’, the response is saved and the updated response visible to all users 
- If clicking on ‘cancel’, the admin gets redirected back and operation is cancelled
- If clicking on `delete response` a confirmation dialog appears. 
- Clicking on ‘cancel’ , admin gets redirected and nothing changes. Clicking on Delete 
- Clicking on ‘confirm delete’ ,the response gets deleted 
- The response is now deleted for all users 

## Tasks:

- [ ] (frontend) create page for admin responses 
- [ ] (frontend) create UI elements for viewing comments and response fields including buttons, text fields and their layout 
- [ ] (frontend) create UI elements such as ‘save response’ buttons for the admin responses to the comments for all type of comments on all pages
- [ ] (backend) add view functions to collect and display all type of comments from DB  
- [ ] (backend) add view functions to delete comments from DB  
- [ ]
