### ISSUE TITLE
USER STORY: Comment on Route 

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#27]
As an authenticated website user, I can leave a comment on a cycling route so that I express my opinion about a it to other users and start a discussion and share tips + tricks 

## Acceptance Criteria: 

- each route that a user has published has an ‘give comment’ button attached 
- After clicking on ‘comment’ button, an text field appears and the users can write their comment 
- after clicking on button to save changes, the comment is saved and visible marked as ‘waiting for approval’
- The site admin can now review the comment,
- The overall product rating is updated accordingly as average of all ratings 

## Tasks:

- [ ] (frontend) create UI elements such as buttons, text fields and their layout 
- [ ] (backend) add view functions to enter comments into DB  
- [ ] (backend) create data structure for comments to reflect feature
