### ISSUE TITLE
USER STORY: Update Product Comment

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#28]
As an authenticated website user, I can update or delete my comments  so that I can edit and delete my previous comments after I have given it when I change my mind

## Acceptance Criteria: 

- each comment has an edit and save button attached 
- After clicking on ‘edit’ button, a text field with the previous comment appears and the user edit the text 
- after clicking on button to save changes, the comment is under ‘waiting for approval’ status again 
- the comment is marked as ‘edited’ or deleted after approval
- After admin approval, the updated comment is visible
- After clicking on button to delete comment, a confirmation dialog appears 
- If clicking on ‘cancel’, the user gets redirected back and operation is cancelled
- if clicking on ‘confirm delete’, the comment is deleted and disappeared from the UI

## Tasks:

- [ ] (frontend) create UI elements for editing comments such as buttons, text fields and their layout 
- [ ] (backend) add view functions to enter updated comments into DB  
- [ ] (backend) add view functions to delete comments from DB  
- [ ] (backend) update data structure for comments to reflect feature
