### ISSUE TITLE
USER STORY: Comment on Product

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#29]
As an authenticated website user, I can leave a comment on a product of my previous orders so that I can further express my opinion about a it to other users 

## Acceptance Criteria: 

- each product that a user has ordered has an ‘give comment’ button attached 
- After clicking on ‘comment’ button, an text field appears and the users can write their comment 
- after clicking on button to save changes, the comment is saved and visible marked as ‘waiting for approval’
- The site admin can now review the comment,
- The overall product rating is updated accordingly as average of all ratings 

## Tasks:

- [x] (frontend) create UI elements such as buttons, text fields and their layout 
- [x] (backend) add view functions to enter comments into DB  
- [x] (backend) create data structure for comments to reflect feature
