### ISSUE TITLE
USER STORY: Update Product Rating

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#30]
As an authenticated website user, I can update or delete my ratings  so that I can edit and delete my previous rating after I have given it when I change my mind

## Acceptance Criteria: 

- each rating has an edit button attached
- After clicking on ‘edit’ button, an interactive field such as slider or option to click on the rating stars appears and the use can change it 
- after clicking on button to save changes, the updated rating is saved
- The overall product rating is updated accordingly as average of all ratings 

## Tasks:

- [ ] (frontend) create UI elements for editing ratings such as buttons, text fields and their layout 
- [ ] (backend) add view functions to enter updated ratings into DB  
- [ ] (backend) add view functions to delete ratings from DB  
- [ ] (backend) update data structure for ratings to reflect feature
