### ISSUE TITLE
USER STORY: Previous Orders Details 

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#32]
As a website user, I can click on a purchase item in my purchase history so that I can retrieve all information linked to this purchase 

## Acceptance Criteria: 

- When a user clicks on an item in the purchase history, he will be directed to a detail view page with all the information containing the order 

## Tasks:

- [x] (FE) Add detail view of an order displaying all information about a particular order
- [x] (BE)  add URL route for sorting and displaying the previous orders   
- [x] (BE) add view function to retrieve a list of the previous orders from the DB and send it to the template
- [x]  (BE) add view function to retrieve a list of the previous orders from the DB and send it to the template
