### ISSUE TITLE
USER STORY: Previous Orders

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#33]
As a website user, I can go to a section of my profile page so that I can see an overview of my previous orders

## Acceptance Criteria: 

- When a user has made one ore more purchases, the orders should be be displayed on their profile page
- They can click on buttons to sort the orders by date, price and category 
- When they click on one of the items of the order history, they will receive a detail view with all information stored about this purchase , including shipping addresses , delivery costs, grand total, 
- all items linked to this purchase are clickable and link to the item in the shop .

## Tasks:

- [ ] (FE) add visual UI element on the profile page template to see an overview of the latest orders 
- [ ] (FE) include buttons to sort the orders, i.e. by date, price or category 
- [ ] (BE)  add URL route for sorting and displaying the previous orders
- [ ] (BE) add view function to retrieve a list of the previous orders from the DB and send it to the template
