### ISSUE TITLE
USER STORY: Notification of Comments from others

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#38]
As a website user, I can get a notification if another user commented, for example via an icon or a preview in the navbar so that I can respond to a comment about the cycling route

## Acceptance Criteria: 

- when another user comments below the comment, a small visual UI element in form of a message/toast/notification should appear for the original user notifying them that someone interacted with them 
- When an admin approved a comment, the user should get a notification element 
- When an admin writes a response to a comment, a notification should appear 

## Tasks:

- [ ] (FE) add visual UI element on the profile page whether someone commented below your comment 
- [ ] (FE) add visual UI element on the notification message to link to the comment 
- [ ] (BE)  add URL route to comment from the notification message  
- [ ] (BE) add view function to navigate user to product that he got notified 
- [ ] (BE) add deletion form for profile
