### ISSUE TITLE
USER STORY: Delete Profile

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#39]
As a website user, I can delete my profile so that I can leave the website and ensure that all my profile data is deleted 

## Acceptance Criteria: 

- when the user clicks on the delete button, a dialog should appear and ask the user to confirm the operation, and also warn that this operation cannot be undone 
-  when user click on 'cancel', operation is cancelled 
- when user click on 'confirm' the entire profile is deleted from the DB 
- user gets a confirmation message that the operation was successful
- after deleting the profile, the user should not be able to login with their credentials any more
 
## Tasks:

- [x] (FE) add button for deleting the profile to the profile page 
- [x] (FE)  add confirmation dialog to make user confirm deletion, and advising that this operation cannot be undone 
- [x] (FE) visual feedback such as a toast whether operation was successful
- [x] (BE) add view function to delete the user  and their profile 
- [x] (BE) add deletion form for profile
