### ISSUE TITLE
USER STORY: Update Profile Details

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#40]
As a website user, I can edit details of my profile such as address or name so that I can keep my details up-to-date, in events such as that the address or name changed after I signed up 

## Acceptance Criteria: 

-  User goes to personal area and can see a list of data stored about them such as email, full name and  address 
- when clicking on the edit button, a form should appear where the user can enter new values to update the information 
- after clicking on ‘save button’ and submitting the form, the edited values should be stored in the DB and displayed in the table 

## Tasks:

- [x] (frontend) Add Profile Page , including layout and UI elements to display the data stored in the DB about the user. 
- [x] (frontend) also include buttons for editing and deleting the profile 
- [x] (frontend) Visual Feedback (such as message or modal) when or if editing was successful
- [x] (backend) add DB model for profile and include appropriate fields such as address, full name, email address 
- [x] (backend) add view function to update fields such as address, full name, email address 
- [x] (backend) add form to update fields such as address, full name, email address
