### ISSUE TITLE
USER STORY: Order By Name

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#41]
As a website user, I can sort the product list by Name so that I can find the cheapest option available for the current category

## Acceptance Criteria: 

- when clicking on the ‘filter by Category’ item, the items are sorted as selected by Name
- For both ascending and descending order 

## Tasks:

- [x] (FE) create UI elements for ‘sort by’ selection box on the product detail page 
- [x] (FE) add implement the sorting functionality by Name to hide elements, for example using Javascript
- [x] (FE) Implement both for  descending and ascending order
