### ISSUE TITLE
USER STORY: View Product Details

### ISSUE THREAD

**Issue by nils-n** [nils-n/city-cycling#45]
As a website user, I can click on a product in the shop to see more details about it so that I can get more information before making a purchase 

## Acceptance Criteria: 

-  when user clicks on a product, a product detail page opens 
- the page should contain all information about the product 

## Tasks:

- [x] (FE) create UI for product detail page 
- [x] (FE) add anchor elements to the shop page directing to the detail page 
- [x] (BE) create URL and view for the product detail page
